### ISSUE TITLE
Inconsistent marks

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#130]
In the bitalloon version (on firefox) some of my marks don't show up in the marked list and can't be found by searching. Refreshing the page does not fix the problem; renaming the marks does. I can't reproduce the problem reliably at all, it's not related in any obvious way to copy or paste, the nodes aren't cloned, etc.  I have about 30 marks.

I can try messing around on master or in a new document, but I don't really know anything beyond that description, so it's not clear if I am in a better position to reproduce than anyone else other than that I know it appears in my browser.

**Comment by WuTheFWasThat** [comment]
yes, the marks datastructure has been incorrect since cloning was introduced.  unfortunately, i didn't realize until a few days ago.  the clones needn't be of the marks themselves to introduce errors.  the bugs (as far as i know) shouldn't affect any behavior except causing the marked list to be wrong.  

I'll probably fix it over the weekend.  I'm curious if you have an opinion or thoughts on implementation though.  here's the stripped down version of the data-structures problem, as I described it to shaunak last night:

you start with a one-vertex DAG.  this vertex is the root, and it's guaranteed to always be a source.  we must support the following operations:
- add node (id): basically does nothing except declare the node exists (it's initially disconnected from everything else).  this should be O(1)
- add edge (src, dst):  this can be assumed to not create cycles (and dst is never root)
- remove edge (src, dst):  this may disconnect parts of the graph (that can later be re-attached via add edge)
- mark node (id, somestring)
- unmark node (id)
- list_marks_reachable_from_root():  this should be O(#marks)

out-degree should be thought of as far bigger than in-degree.  so mental model is something like:

O(1)  < O(ancestors) ~= O(#marks) << O(descendants) < O(N)

The easiest thing to do is to do basically nothing, and make list_marks do a reachability test for each mark known.  The other idea i had is to maintain the number of paths to each mark, for each node.  i'm not sure what's better, or if there's something better.

**Comment by WuTheFWasThat** [comment]
this is fixed now.  the data format is inconsistent though, sorry.  to backfill (you have to do this in javascript console for each document...):

```var my_document = window.location.pathname.split('/')[1];
for (key in localStorage) {
  if (key.match(/.*:marks$/)) {
    var parts = key.split(':');
    if ((parts.length === 3) && (parts[2] === 'marks') && (parts[0] === (my_document + 'save'))) {
      var id = parseInt(parts[1]);
      var mark = JSON.parse(localStorage[key])[id];
      if (mark) {
        console.log(id, mark);
        view.do(new SetMark(id, mark));
      }
    }
  }
}```

**Comment by paulfchristiano** [comment]
When I paste that into the javascript console (firefox, bitballoon branch)
I get: ReferenceError: SetMark is not defined. How should I run it?

**Comment by WuTheFWasThat** [comment]
are you sure you're on the latest bitballoon code?  SetMark appears to be defined for me, at least in chrome

**Comment by paulfchristiano** [comment]
I did a hard refresh, at vimflowy.bitballoon.com, and then tried clearing
my cache. In response to this comment I also tried clearing "cookies and
other site and plugin data," and then it works.

It works in incognito mode in firefox. Maybe clearing site data would cause
it to work, but the analogous chrome option also destroyed the document.

Restoring the marks isn't super important.

**Comment by paulfchristiano** [comment]
Sorry, it was easy---the marks plugin was disabled on my old account, but
enabled by default on new accounts.

On Mon, Dec 14, 2015 at 12:01 PM, Paul Christiano <paulfchristiano@gmail.com

**Comment by paulfchristiano** [comment]
Though after updating, when I type ' I receive:

 ERROR:

 Error: Assertion error: No canonical instance found for id: 3
Expected false to be true

 Error: Assertion error: No canonical instance found for id: 3
Expected false to be true

 errorFactory/g@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:15913:22
exports.assert@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:15943:15
Data.prototype.canonicalInstance@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:17652:7
Data.prototype.canonicalInstance@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:17650:25
enableMarks/</this.view.menu</</findMarks@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/0c1a5e7e64b81b79a877acd270c279bb79ecd156.js:3:47
enableMarks/</this.view.menu</<@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/0c1a5e7e64b81b79a877acd270c279bb79ecd156.js:3:218
Menu.prototype.update@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:21604:24
.every@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:16463:9
Mode.prototype.every@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:16332:18
KeyHandler.prototype.processMode@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:16962:12
KeyHandler.prototype.processOnce@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:16888:16
KeyHandler.prototype.processKeys@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:16881:22
KeyHandler.prototype.handleKey@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:16872:19
EventEmitter.prototype.emit/<@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:16181:24
EventEmitter.prototype.emit@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:16175:1
KeyEmitter.prototype.listen/</<@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:16697:21
n.event.dispatch@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:3:6352
n.event.add/r.handle@
http://bitballoon.scdn4.secure.raxcdn.com/bundles/dfb7ea37f775318292a8a34b4a19b50a7984ca2a.js:3:3162

**Comment by WuTheFWasThat** [comment]
i think your traceback suggests you're still running old code

**Comment by WuTheFWasThat** [comment]
ok was my bad, and it's fixed now

**Comment by WuTheFWasThat** [comment]
sorry, i messed up - tests were passing but i forgot about some state from older versions of vimflowy.  this undoes the old backfill and redoes new backfill...

```
var my_document = window.location.pathname.split('/')[1];
for (key in localStorage) {
  if (key.match(/.*:marks$/)) {
    var parts = key.split(':');
    if ((parts.length === 3) && (parts[2] === 'marks') && (parts[0] === (my_document + 'save'))) {
      var id = parseInt(parts[1]);
      var mark = JSON.parse(localStorage[key])[id];
      if (mark) {
        console.log(id, mark);
        try {view.do(new UnsetMark(id, mark));} catch (e) {}
        if (view.data.canonicalInstance(id)) {
          view.do(new SetMark(id, mark));
        }
      }
    }
  }
}
```
