### ISSUE TITLE
module is not defined

### ISSUE THREAD

**Issue by alxgnon** [WuTheFWasThat/vimflowy#150]
I followed the instructions to set up the project for development.

When I connect to localhost:8080, I get 21 javascript errors. I believe they are all related.

The first one is: `Uncaught ReferenceError: module is not defined` in `lodash.js:1`.

All the others seem to be caused by the module global not being defined, and so module loading not working correctly. 

I looked in the dependencies for a library providing module loading and I couldn't find one. This is where I decided it would be best to open an issue rather than to try to guess how the application works by myself.

**Comment by WuTheFWasThat** [comment]
thanks for reporting this.  I've fixed it: https://github.com/WuTheFWasThat/vimflowy/commit/906febd7a373de0fee5dd0de16b780dc195a638f

however, it's somewhat unsatisfactory, since it could break again if lodash changes the way their project is structured.  My problem is basically this:  I want the node unit tests and browser to be using the same versions of libraries, and node uses npm install.  thus, I use a hardcoded location to define the location the client should get lodash from.  (if you know of any module loading library that solves this problem, let me know)

also, nice to see new people installing vimflowy!

**Comment by alxgnon** [comment]
Thank you for fixing this.

I submitted a new issue https://github.com/WuTheFWasThat/vimflowy/issues/151 that came up. I'm determined to get the development version to work on my laptop.

**Comment by WuTheFWasThat** [comment]
sorry for the issues, and thanks for your persistence ... looking into #151 now.
