### ISSUE TITLE
Backspace doesn't work when holding shift

### ISSUE THREAD

**Issue by alxgnon** [WuTheFWasThat/vimflowy#158]

**Comment by WuTheFWasThat** [comment]
shift+backspace in insert mode deletes the next character.  i realize this is not standard, and i put it mainly because i personally liked it.  i'll fix it tonight though - eventually there should be a key remapping feature (i had a branch in progress for this, but i had abandoned it b/c it was a little trickier than i had initially thought)

**Comment by WuTheFWasThat** [comment]
fixed: https://github.com/WuTheFWasThat/vimflowy/commit/40ff0d447bd6df41992c5d775445c3f648de6041
