### ISSUE TITLE
search doesn't display marks

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#187]
##

**Comment by fullyint** [comment]
In case the code for "marks in search" relates to code for "marks in breadcrumbs", perhaps it would be convenient to address both at the same time. Consider this:
- [mark_1] text 1
  - 1a
- [mark_2]
  - 2a

I'm guessing it's an intentional space-saver to omit marks in some breadcrumbs, e.g., the current
>  :house: > text 1 > 1a

is probably better than what does _not_ happen:
>  :house: > [mark_1] text 1 > 1a

-----
However, I find myself wanting mark-only items, like [mark_2] in the outline above. But breadcrumbs: 
  :house: >   > 2a

So, I've been doing this for the sake of breadcrumbs:
- [mark_2] @mark_2
  - 2a

>  :house: > @mark_2 > 2a

It's a bit redundant in the outline to have [mark_2] @mark_2. If easy, it might be nice to show marks in breadcrumbs for items that are mark-only. It's not a huge deal though. And maybe there is a reason (unknown to me) to avoid mark-only items.

**Comment by WuTheFWasThat** [comment]
i actually used to have the marks displayed in both breadcrumbs and search, but lost it in a refactor and didn't notice.  so that should be fixed as well, imo

**Comment by WuTheFWasThat** [comment]
shown in search: d4b50e70d995d4277724555204af45da36544d3e
and in breadcrumbs: ea43b2fd27510a4418716f80e17e076336a50473
