### ISSUE TITLE
make storage be local instead of in localstorage [$100]

### ISSUE THREAD

**Issue by tsvibt** [WuTheFWasThat/vimflowy#191]
Unless there's some performance consideration, in which case figure out a good autobackup system.

**Comment by gunar** [comment]
What do you mean by "local"? I can only think of IndexedDB.

**Comment by tsvibt** [comment]
I'm not a developer, so the thing I'm saying might be nonsensical (perhaps for reasons of security architecture or something). What I want is to edit vimflowy docs in my browser (for the resulting workflow) but have them stored and updated automatically as ordinary files in a readable format somewhere I can find them. Then I don't need to manually back things up, and I don't have to worry about vimflowy getting messed up (e.g. by going over localstorage bounds, which has happened to me), and there's fewer steps to exporting docs, and I can conveniently do normal text editing if I so choose. In my head this just happens by having vimflowy have some files in its directory that it manages, which store the docs. (And it only has permission to read those files or something? This is where my understanding is completely blank.)

**Comment by gunar** [comment]
@tsvibt thank you for explaining your situation.

Common in-browser webapp have no permission to actively edit local files. One could convert Vimflowy into a [cross-platform native app](https://github.com/electron/electron) (think executables for Windows, Linux and Mac). I have never coded such a thing, but I presume it must take a lot of development hours in order for it to work as expected.

But instead of doing that, I would rather have Vimflowy save all my nodes in the cloud, just like Workflowy does, so I can access it from any device with no fear of loss of data.

**Comment by gunar** [comment]
Just realized this is a duplicated issue. See #123.

Related to saving data to cloud, see #124.

**Comment by tsvibt** [comment]
Thanks, this is helpful! I wonder if there's a short path to this functionality through Dropbox. That is, vimflowy sends stuff to my Dropbox automatically, and it thereby appears locally, where I can see and edit it normally. (Workflowy does something like this.) 

(I didn't figure out in 3 mins how to migrate bounties, so if the dropbox thing doesn't work I'll just post in those issues.)

**Comment by WuTheFWasThat** [comment]
It would probably need to be a desktop app to do this.  I'd made an issue for that as well :) #194

**Comment by gunar** [comment]
@WuTheFWasThat Perhaps close this issue then? :innocent:

**Comment by WuTheFWasThat** [comment]
closing in favor of https://github.com/WuTheFWasThat/vimflowy/issues/203
