### ISSUE TITLE
Click location to move cursor

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#8]

**Comment by WuTheFWasThat** [comment]
i tried to do this.  https://github.com/WuTheFWasThat/vimflowy/commit/4fd7c268b903ac2f198bb579099ec3eb00f1d0c9

but it made the rendering noticeably slower... I think it was due to making more divs (as opposed to binding the click handler).  brief search turned up this:  http://stackoverflow.com/questions/11752300/how-to-determine-character-in-textnode-that-was-clicked-on

seems like doing it properly might be a bit gross...

**Comment by WuTheFWasThat** [comment]
https://github.com/WuTheFWasThat/vimflowy/commit/4c93336d01531ad0e8ac6da2941c42f1ead0df86
